language: node_js
node_js:
- '10'
script: yarn build
deploy:
  provider: npm
  email: npm@netflix.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: Mmc7ol87n8tznfkjddtk2EiLYd+8zYLiJOgY3fm6di1daKiFC4yCUC9FVCEvdzbxJmDEa2XWom3d5R4lfPnRONwbJ5sO1xD6SFQIw8jYzByfEEc/dBl3XlYZREg3KEwZC0K/wlNQWjC2y0kYomYQD7+HLrxn5Ch0oF4Kt0/euSuEIo98raocaTEaUBgufteE0eJDYJczr6XWugIUBRKhI7Hy8pIN2rrpMCkGiNGuqGsz11F2o/3eqheqMDjVeQh+zc89roVb5mUZaDJqHjnBS6Y2Bf8qWzEhk+UItfWwupRA1VLWYljLF3ZdA3B9pk/X/wQY+116onUGikXLgnT0Ss8bOdmdmuDcvC+82Q1i9X4M6qSCnXpGxJUlbtYDt3sBKR66Fp/Z1dD7SpvCHvrItFkcGBxBqnD15INMjsOQIOq3//D8xfsFUOi0OZTW+bW4JsgV7CksVfHo1UoAcmLvTKI/HEAteh5DyOzAM5wEXPsxJBqFP6cutqTE9xNoOBRaSHR4HOMp96q5ms0yIGC2a4y409nvVDTQm1oLHr4d0kck5pVbRevK1t+F4+bqTp4wVT3YmbroaB1gQ3CfNbLJMhbkuvXRnxUdC6VvTfoQV4/QTdtk1rNmT+AqtrPx/ORz4UxQNNlEqr60yy0jM+F84VMtsf4cjQxoQdHmhZXwq4s=
